name: telegram-thumbnail-generator-bot
services:
  - name: telegram-bot
    type: web
    runtime: nodejs16
    git:
      repository: YOURGITREPO/telegram-thumbnail-generator-bot
      branch: main
    build:
      builder: dockerfile
    ports:
      - port: 8080
    env:
      - name: NODE_ENV
        value: production
      - name: BOT_TOKEN
        value: 6866329408:AAGbn9Cd6V5f10TcNsec4h9yTposBWd2okI
    scaling:
      min: 1
      max: 1
